// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAlDQD3VReuVH4clvlsLycdQc555WBYjgU',
    appId: '1:514338142727:android:766bef3e674736eef308a2',
    messagingSenderId: '514338142727',
    projectId: 'boring-app-d675d',
    databaseURL: 'https://boring-app-d675d-default-rtdb.firebaseio.com',
    storageBucket: 'boring-app-d675d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAGrHFxF0oDKdfzuk-FYcOXKsM8bfDSjk8',
    appId: '1:514338142727:ios:09069f3a7543351ef308a2',
    messagingSenderId: '514338142727',
    projectId: 'boring-app-d675d',
    databaseURL: 'https://boring-app-d675d-default-rtdb.firebaseio.com',
    storageBucket: 'boring-app-d675d.appspot.com',
    iosClientId: '514338142727-fdngsbtg0p0uno0rvraatfc5cgpdk6g2.apps.googleusercontent.com',
    iosBundleId: 'com.example.boringApp',
  );
}
